server {
    listen 80;
    server_name your-domain.com;  # Замените на ваш IP или домен

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /home/username/lms_project/staticfiles/;
    }

    location /media/ {
        alias /home/username/lms_project/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/username/lms_project/lms.sock;
    }
}